// Surah-metadata (114 surahs, Hafs-telling, totaal 6236 verzen).
// Bron: risan/quran-json. name=Arabisch, tr=transliteratie, en=betekenis,
// verses=aantal verzen, type=m(eccan)/d(medinan).
export const SURAHS = [
  {
    id: 1,
    name: "الفاتحة",
    tr: "Al-Fatihah",
    en: "The Opener",
    verses: 7,
    type: "m",
  },
  {
    id: 2,
    name: "البقرة",
    tr: "Al-Baqarah",
    en: "The Cow",
    verses: 286,
    type: "d",
  },
  {
    id: 3,
    name: "آل عمران",
    tr: "Ali 'Imran",
    en: "Family of Imran",
    verses: 200,
    type: "d",
  },
  {
    id: 4,
    name: "النساء",
    tr: "An-Nisa",
    en: "The Women",
    verses: 176,
    type: "d",
  },
  {
    id: 5,
    name: "المائدة",
    tr: "Al-Ma'idah",
    en: "The Table Spread",
    verses: 120,
    type: "d",
  },
  {
    id: 6,
    name: "الأنعام",
    tr: "Al-An'am",
    en: "The Cattle",
    verses: 165,
    type: "m",
  },
  {
    id: 7,
    name: "الأعراف",
    tr: "Al-A'raf",
    en: "The Heights",
    verses: 206,
    type: "m",
  },
  {
    id: 8,
    name: "الأنفال",
    tr: "Al-Anfal",
    en: "The Spoils of War",
    verses: 75,
    type: "d",
  },
  {
    id: 9,
    name: "التوبة",
    tr: "At-Tawbah",
    en: "The Repentance",
    verses: 129,
    type: "d",
  },
  { id: 10, name: "يونس", tr: "Yunus", en: "Jonah", verses: 109, type: "m" },
  { id: 11, name: "هود", tr: "Hud", en: "Hud", verses: 123, type: "m" },
  { id: 12, name: "يوسف", tr: "Yusuf", en: "Joseph", verses: 111, type: "m" },
  {
    id: 13,
    name: "الرعد",
    tr: "Ar-Ra'd",
    en: "The Thunder",
    verses: 43,
    type: "d",
  },
  {
    id: 14,
    name: "إبراهيم",
    tr: "Ibrahim",
    en: "Abraham",
    verses: 52,
    type: "m",
  },
  {
    id: 15,
    name: "الحجر",
    tr: "Al-Hijr",
    en: "The Rocky Tract",
    verses: 99,
    type: "m",
  },
  {
    id: 16,
    name: "النحل",
    tr: "An-Nahl",
    en: "The Bee",
    verses: 128,
    type: "m",
  },
  {
    id: 17,
    name: "الإسراء",
    tr: "Al-Isra",
    en: "The Night Journey",
    verses: 111,
    type: "m",
  },
  {
    id: 18,
    name: "الكهف",
    tr: "Al-Kahf",
    en: "The Cave",
    verses: 110,
    type: "m",
  },
  { id: 19, name: "مريم", tr: "Maryam", en: "Mary", verses: 98, type: "m" },
  { id: 20, name: "طه", tr: "Taha", en: "Ta-Ha", verses: 135, type: "m" },
  {
    id: 21,
    name: "الأنبياء",
    tr: "Al-Anbya",
    en: "The Prophets",
    verses: 112,
    type: "m",
  },
  {
    id: 22,
    name: "الحج",
    tr: "Al-Hajj",
    en: "The Pilgrimage",
    verses: 78,
    type: "d",
  },
  {
    id: 23,
    name: "المؤمنون",
    tr: "Al-Mu'minun",
    en: "The Believers",
    verses: 118,
    type: "m",
  },
  {
    id: 24,
    name: "النور",
    tr: "An-Nur",
    en: "The Light",
    verses: 64,
    type: "d",
  },
  {
    id: 25,
    name: "الفرقان",
    tr: "Al-Furqan",
    en: "The Criterion",
    verses: 77,
    type: "m",
  },
  {
    id: 26,
    name: "الشعراء",
    tr: "Ash-Shu'ara",
    en: "The Poets",
    verses: 227,
    type: "m",
  },
  {
    id: 27,
    name: "النمل",
    tr: "An-Naml",
    en: "The Ant",
    verses: 93,
    type: "m",
  },
  {
    id: 28,
    name: "القصص",
    tr: "Al-Qasas",
    en: "The Stories",
    verses: 88,
    type: "m",
  },
  {
    id: 29,
    name: "العنكبوت",
    tr: "Al-'Ankabut",
    en: "The Spider",
    verses: 69,
    type: "m",
  },
  {
    id: 30,
    name: "الروم",
    tr: "Ar-Rum",
    en: "The Romans",
    verses: 60,
    type: "m",
  },
  { id: 31, name: "لقمان", tr: "Luqman", en: "Luqman", verses: 34, type: "m" },
  {
    id: 32,
    name: "السجدة",
    tr: "As-Sajdah",
    en: "The Prostration",
    verses: 30,
    type: "m",
  },
  {
    id: 33,
    name: "الأحزاب",
    tr: "Al-Ahzab",
    en: "The Combined Forces",
    verses: 73,
    type: "d",
  },
  { id: 34, name: "سبإ", tr: "Saba", en: "Sheba", verses: 54, type: "m" },
  {
    id: 35,
    name: "فاطر",
    tr: "Fatir",
    en: "Originator",
    verses: 45,
    type: "m",
  },
  { id: 36, name: "يس", tr: "Ya-Sin", en: "Ya Sin", verses: 83, type: "m" },
  {
    id: 37,
    name: "الصافات",
    tr: "As-Saffat",
    en: "Those who set the Ranks",
    verses: 182,
    type: "m",
  },
  {
    id: 38,
    name: "ص",
    tr: "Sad",
    en: 'The Letter "Saad"',
    verses: 88,
    type: "m",
  },
  {
    id: 39,
    name: "الزمر",
    tr: "Az-Zumar",
    en: "The Troops",
    verses: 75,
    type: "m",
  },
  {
    id: 40,
    name: "غافر",
    tr: "Ghafir",
    en: "The Forgiver",
    verses: 85,
    type: "m",
  },
  {
    id: 41,
    name: "فصلت",
    tr: "Fussilat",
    en: "Explained in Detail",
    verses: 54,
    type: "m",
  },
  {
    id: 42,
    name: "الشورى",
    tr: "Ash-Shuraa",
    en: "The Consultation",
    verses: 53,
    type: "m",
  },
  {
    id: 43,
    name: "الزخرف",
    tr: "Az-Zukhruf",
    en: "The Ornaments of Gold",
    verses: 89,
    type: "m",
  },
  {
    id: 44,
    name: "الدخان",
    tr: "Ad-Dukhan",
    en: "The Smoke",
    verses: 59,
    type: "m",
  },
  {
    id: 45,
    name: "الجاثية",
    tr: "Al-Jathiyah",
    en: "The Crouching",
    verses: 37,
    type: "m",
  },
  {
    id: 46,
    name: "الأحقاف",
    tr: "Al-Ahqaf",
    en: "The Wind-Curved Sandhills",
    verses: 35,
    type: "m",
  },
  {
    id: 47,
    name: "محمد",
    tr: "Muhammad",
    en: "Muhammad",
    verses: 38,
    type: "d",
  },
  {
    id: 48,
    name: "الفتح",
    tr: "Al-Fath",
    en: "The Victory",
    verses: 29,
    type: "d",
  },
  {
    id: 49,
    name: "الحجرات",
    tr: "Al-Hujurat",
    en: "The Rooms",
    verses: 18,
    type: "d",
  },
  {
    id: 50,
    name: "ق",
    tr: "Qaf",
    en: 'The Letter "Qaf"',
    verses: 45,
    type: "m",
  },
  {
    id: 51,
    name: "الذاريات",
    tr: "Adh-Dhariyat",
    en: "The Winnowing Winds",
    verses: 60,
    type: "m",
  },
  {
    id: 52,
    name: "الطور",
    tr: "At-Tur",
    en: "The Mount",
    verses: 49,
    type: "m",
  },
  {
    id: 53,
    name: "النجم",
    tr: "An-Najm",
    en: "The Star",
    verses: 62,
    type: "m",
  },
  {
    id: 54,
    name: "القمر",
    tr: "Al-Qamar",
    en: "The Moon",
    verses: 55,
    type: "m",
  },
  {
    id: 55,
    name: "الرحمن",
    tr: "Ar-Rahman",
    en: "The Beneficent",
    verses: 78,
    type: "d",
  },
  {
    id: 56,
    name: "الواقعة",
    tr: "Al-Waqi'ah",
    en: "The Inevitable",
    verses: 96,
    type: "m",
  },
  {
    id: 57,
    name: "الحديد",
    tr: "Al-Hadid",
    en: "The Iron",
    verses: 29,
    type: "d",
  },
  {
    id: 58,
    name: "المجادلة",
    tr: "Al-Mujadila",
    en: "The Pleading Woman",
    verses: 22,
    type: "d",
  },
  {
    id: 59,
    name: "الحشر",
    tr: "Al-Hashr",
    en: "The Exile",
    verses: 24,
    type: "d",
  },
  {
    id: 60,
    name: "الممتحنة",
    tr: "Al-Mumtahanah",
    en: "She that is to be examined",
    verses: 13,
    type: "d",
  },
  {
    id: 61,
    name: "الصف",
    tr: "As-Saf",
    en: "The Ranks",
    verses: 14,
    type: "d",
  },
  {
    id: 62,
    name: "الجمعة",
    tr: "Al-Jumu'ah",
    en: "The Congregation, Friday",
    verses: 11,
    type: "d",
  },
  {
    id: 63,
    name: "المنافقون",
    tr: "Al-Munafiqun",
    en: "The Hypocrites",
    verses: 11,
    type: "d",
  },
  {
    id: 64,
    name: "التغابن",
    tr: "At-Taghabun",
    en: "The Mutual Disillusion",
    verses: 18,
    type: "d",
  },
  {
    id: 65,
    name: "الطلاق",
    tr: "At-Talaq",
    en: "The Divorce",
    verses: 12,
    type: "d",
  },
  {
    id: 66,
    name: "التحريم",
    tr: "At-Tahrim",
    en: "The Prohibition",
    verses: 12,
    type: "d",
  },
  {
    id: 67,
    name: "الملك",
    tr: "Al-Mulk",
    en: "The Sovereignty",
    verses: 30,
    type: "m",
  },
  {
    id: 68,
    name: "القلم",
    tr: "Al-Qalam",
    en: "The Pen",
    verses: 52,
    type: "m",
  },
  {
    id: 69,
    name: "الحاقة",
    tr: "Al-Haqqah",
    en: "The Reality",
    verses: 52,
    type: "m",
  },
  {
    id: 70,
    name: "المعارج",
    tr: "Al-Ma'arij",
    en: "The Ascending Stairways",
    verses: 44,
    type: "m",
  },
  { id: 71, name: "نوح", tr: "Nuh", en: "Noah", verses: 28, type: "m" },
  {
    id: 72,
    name: "الجن",
    tr: "Al-Jinn",
    en: "The Jinn",
    verses: 28,
    type: "m",
  },
  {
    id: 73,
    name: "المزمل",
    tr: "Al-Muzzammil",
    en: "The Enshrouded One",
    verses: 20,
    type: "m",
  },
  {
    id: 74,
    name: "المدثر",
    tr: "Al-Muddaththir",
    en: "The Cloaked One",
    verses: 56,
    type: "m",
  },
  {
    id: 75,
    name: "القيامة",
    tr: "Al-Qiyamah",
    en: "The Resurrection",
    verses: 40,
    type: "m",
  },
  {
    id: 76,
    name: "الإنسان",
    tr: "Al-Insan",
    en: "The Man",
    verses: 31,
    type: "d",
  },
  {
    id: 77,
    name: "المرسلات",
    tr: "Al-Mursalat",
    en: "The Emissaries",
    verses: 50,
    type: "m",
  },
  {
    id: 78,
    name: "النبإ",
    tr: "An-Naba",
    en: "The Tidings",
    verses: 40,
    type: "m",
  },
  {
    id: 79,
    name: "النازعات",
    tr: "An-Nazi'at",
    en: "Those who drag forth",
    verses: 46,
    type: "m",
  },
  {
    id: 80,
    name: "عبس",
    tr: "'Abasa",
    en: "He Frowned",
    verses: 42,
    type: "m",
  },
  {
    id: 81,
    name: "التكوير",
    tr: "At-Takwir",
    en: "The Overthrowing",
    verses: 29,
    type: "m",
  },
  {
    id: 82,
    name: "الإنفطار",
    tr: "Al-Infitar",
    en: "The Cleaving",
    verses: 19,
    type: "m",
  },
  {
    id: 83,
    name: "المطففين",
    tr: "Al-Mutaffifin",
    en: "The Defrauding",
    verses: 36,
    type: "m",
  },
  {
    id: 84,
    name: "الإنشقاق",
    tr: "Al-Inshiqaq",
    en: "The Sundering",
    verses: 25,
    type: "m",
  },
  {
    id: 85,
    name: "البروج",
    tr: "Al-Buruj",
    en: "The Mansions of the Stars",
    verses: 22,
    type: "m",
  },
  {
    id: 86,
    name: "الطارق",
    tr: "At-Tariq",
    en: "The Nightcommer",
    verses: 17,
    type: "m",
  },
  {
    id: 87,
    name: "الأعلى",
    tr: "Al-A'la",
    en: "The Most High",
    verses: 19,
    type: "m",
  },
  {
    id: 88,
    name: "الغاشية",
    tr: "Al-Ghashiyah",
    en: "The Overwhelming",
    verses: 26,
    type: "m",
  },
  {
    id: 89,
    name: "الفجر",
    tr: "Al-Fajr",
    en: "The Dawn",
    verses: 30,
    type: "m",
  },
  {
    id: 90,
    name: "البلد",
    tr: "Al-Balad",
    en: "The City",
    verses: 20,
    type: "m",
  },
  {
    id: 91,
    name: "الشمس",
    tr: "Ash-Shams",
    en: "The Sun",
    verses: 15,
    type: "m",
  },
  {
    id: 92,
    name: "الليل",
    tr: "Al-Layl",
    en: "The Night",
    verses: 21,
    type: "m",
  },
  {
    id: 93,
    name: "الضحى",
    tr: "Ad-Duhaa",
    en: "The Morning Hours",
    verses: 11,
    type: "m",
  },
  {
    id: 94,
    name: "الشرح",
    tr: "Ash-Sharh",
    en: "The Relief",
    verses: 8,
    type: "m",
  },
  { id: 95, name: "التين", tr: "At-Tin", en: "The Fig", verses: 8, type: "m" },
  {
    id: 96,
    name: "العلق",
    tr: "Al-'Alaq",
    en: "The Clot",
    verses: 19,
    type: "m",
  },
  {
    id: 97,
    name: "القدر",
    tr: "Al-Qadr",
    en: "The Power",
    verses: 5,
    type: "m",
  },
  {
    id: 98,
    name: "البينة",
    tr: "Al-Bayyinah",
    en: "The Clear Proof",
    verses: 8,
    type: "d",
  },
  {
    id: 99,
    name: "الزلزلة",
    tr: "Az-Zalzalah",
    en: "The Earthquake",
    verses: 8,
    type: "d",
  },
  {
    id: 100,
    name: "العاديات",
    tr: "Al-'Adiyat",
    en: "The Courser",
    verses: 11,
    type: "m",
  },
  {
    id: 101,
    name: "القارعة",
    tr: "Al-Qari'ah",
    en: "The Calamity",
    verses: 11,
    type: "m",
  },
  {
    id: 102,
    name: "التكاثر",
    tr: "At-Takathur",
    en: "The Rivalry in world increase",
    verses: 8,
    type: "m",
  },
  {
    id: 103,
    name: "العصر",
    tr: "Al-'Asr",
    en: "The Declining Day",
    verses: 3,
    type: "m",
  },
  {
    id: 104,
    name: "الهمزة",
    tr: "Al-Humazah",
    en: "The Traducer",
    verses: 9,
    type: "m",
  },
  {
    id: 105,
    name: "الفيل",
    tr: "Al-Fil",
    en: "The Elephant",
    verses: 5,
    type: "m",
  },
  { id: 106, name: "قريش", tr: "Quraysh", en: "Quraysh", verses: 4, type: "m" },
  {
    id: 107,
    name: "الماعون",
    tr: "Al-Ma'un",
    en: "The Small kindnesses",
    verses: 7,
    type: "m",
  },
  {
    id: 108,
    name: "الكوثر",
    tr: "Al-Kawthar",
    en: "The Abundance",
    verses: 3,
    type: "m",
  },
  {
    id: 109,
    name: "الكافرون",
    tr: "Al-Kafirun",
    en: "The Disbelievers",
    verses: 6,
    type: "m",
  },
  {
    id: 110,
    name: "النصر",
    tr: "An-Nasr",
    en: "The Divine Support",
    verses: 3,
    type: "d",
  },
  {
    id: 111,
    name: "المسد",
    tr: "Al-Masad",
    en: "The Palm Fiber",
    verses: 5,
    type: "m",
  },
  {
    id: 112,
    name: "الإخلاص",
    tr: "Al-Ikhlas",
    en: "The Sincerity",
    verses: 4,
    type: "m",
  },
  {
    id: 113,
    name: "الفلق",
    tr: "Al-Falaq",
    en: "The Daybreak",
    verses: 5,
    type: "m",
  },
  { id: 114, name: "الناس", tr: "An-Nas", en: "Mankind", verses: 6, type: "m" },
];

export const TOTAL_AYAT = SURAHS.reduce((s, x) => s + x.verses, 0); // 6236
export const surahById = (id) => SURAHS.find((s) => s.id === id);
